### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by FabioFleitas**
Added error handling with the API calls. By default, the API calls return a dictionary (as it did previously). However, now you can specify `PhaxioApi(key, secret, raise_errors=True)` which will raise the following errors:
* `AuthenticationError` - key/secret are invalid
* `APIError` - error with api call
* `ServerError` - server had an error and could not complete your request

These errors can be imported from the `phaxio.errors` module.

To keep legacy code from not breaking, `raise_errors=False` by default.

I also added unit tests that can be run using `python setup.py test` & redid the `manual.py` to be a `unittest`.

### CODE REVIEW

**Comment by FabioFleitas** [comment]
@jfialkoff - just wanted to bump this up. I'm sure you're busy, but would love to get any feedback from you on the pull request.

**Comment by jfialkoff** [comment]
Hey Fabio, I'm not really using the library anymore. I'm happy to make you
a contributor though. Let me know.

On Tue, Sep 22, 2015 at 3:58 PM, Fabio Fleitas <notifications@github.com>
wrote:

> @jfialkoff <https://github.com/jfialkoff> - just wanted to bump this up.
> I'm sure you're busy, but would love to get any feedback from you on the
> pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/setaris/pyphaxio/pull/2#issuecomment-142401591>.
>



-- 
Joshua Fialkoff - Setaris Corporation
307 East 93rd St. #1RW New York, NY 10128
Direct: (646) 257-3812 + Skype: jfialkoffatsetaris
Office: (212) 369-1263 + Website: www.setaris.com

**Comment by FabioFleitas** [comment]
@jfialkoff - yeah I'd be happy to be included as a contributor to help maintain the library.

**Comment by jfialkoff** [comment]
@FabioFleitas - all set. Thanks!

**Comment by FabioFleitas** [comment]
@jfialkoff - Great! Just merged in the changes. I'd like to be able to update the PyPI package as well with any changes. How could we set that up?

**Comment by jfialkoff** [comment]
I'll add you. What's your PyPi username?

**Comment by FabioFleitas** [comment]
It's FabioFleitas

On Monday, September 28, 2015, jfialkoff <notifications@github.com> wrote:

> I'll add you. What's your PyPi username?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfialkoff/pyphaxio/pull/2#issuecomment-143787098>.
>


-- 
Fabio Fleitas
Head of Engineering | Tesorio
813.802.9654
www.tesorio.com

**Comment by jfialkoff** [comment]
You've been added. Thanks!

**Pull request merged**
